# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bd1ef632658c84dbb5efbcde0151da76bfc45318cd518025ee25dd94d0f6f0bdd40aa49b2ddd9e2211ec5e898c10b583425ff1b059b76df1e4a082fe1a457b4

test:
  secret_key_base: efeac19a0389be644877bb1cd08a7ba7d93de929158570715843949bc9034328fb4031199a39dfe44dca926c1ab866748317fee88bd412b8deed1472c3ac1581

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
